version: 0.2

env:
  variables:
    ENV: "sr-ce-test"

phases:
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
  build:
    commands:
      - terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=${TF_VAR_candidate}.tfstate"
      - terraform destroy -auto-approve

